.Dd August 18, 2025
.Dt TRUCOTRICKS 6
.Sh NAME
.Nm trucotricks
.Nd Truco helper memorization tool.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
A helper tool for the Uruguayan card game truco. Each card gets a 2–3 letter code to make sharing hands easier and to aid with memorization of the deck.
.Sh KEYBOARD BINDINGS
.Bl -tag -width indent
.It F1
Show hints.
.It F5
Refresh current scene.
.It 1
Switch to speed game mode.
.It 2
Switch to decode game mode.
.It 3
Switch to encode game mode.
.It 4
Switch to memorize game mode.
.It A-Z
Append that letter to the current guess.
.It Enter
Submit guess.
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/trucotricks/issues
